<?php


class User_validation {

    private $data;
    private $errors = [];
    private static $fields = ['firstname', 'surname', 'email', 'tel', 'username','password', 'password_confirm','lib_code'];
        
    public function __construct($post_data) {
        $this->data = $post_data; 
    }
    
    public function validateForm(){
      foreach(self::$fields as $field) {
          if (!array_key_exists($field, $this->data)){
              trigger_error("$field is missing, please enter.");
              return;
          }
      }  
     $this->validateFirstname();
     $this->validateSurname();
     $this->validateEmail();
     $this->validateTel();
     $this->validateUsername();
     $this->validatePassword();
     $this->validatePasswordConfirm();
     $this->validateLibCode();
     return $this->errors;
    }
    
    private function validateFirstname() { //private functions to be run only within this class, then passed into function validateForm above
        
        $val = trim($this->data['firstname']);
        $cleanFirstname=filter_var($val, FILTER_SANITIZE_STRING);
        if(!preg_match('/^[a-zA-Z0-9]{1,20}$/', $cleanFirstname)){//regular expression
        $this->addError('firstname', 'firstname must be between 1 and 20 characters and alphanumeric.');
        }   else {
            echo "";
            }
        }
    
    
    private function validateSurname() {
       $val = trim($this->data['surname']);
       $cleanSurname=filter_var($val, FILTER_SANITIZE_STRING);
        if(!preg_match('/^[a-zA-Z0-9]{1,20}$/', $cleanSurname)){//regular expression
                $this->addError('surname', 'Surname must be between 1 and 20 characters and alphanumeric.');
        }   else {
            echo "";
            }
        } 
    
    private function validateEmail() {
      $val = trim($this->data['email']);
      $cleanEmail = filter_var($val, FILTER_SANITIZE_EMAIL);
        if(!filter_var($cleanEmail, FILTER_VALIDATE_EMAIL)) {
                $this->addError('email', 'Email must be a valid email.');
        }   else {
            echo "";
            }
        }  
    
    private function validateTel() {
        $val = trim($this->data['tel']);
        $cleanTel = filter_var($val,FILTER_SANITIZE_NUMBER_INT);
        if(!preg_match('/^[0-9]{9,13}$/', $cleanTel)){//regular expression
                $this->addError('tel', 'Telephone must be between 9 and 13 characters and numeric.');
        }   else {
            echo "";
            }
        }  
    
    private function validateUsername() {
       $val = trim($this->data['username']);
       $cleanUsername = filter_var($val, FILTER_SANITIZE_STRING);
        //insert code to check if username already exists in DB when connections learned
        if(!preg_match('/^[a-zA-Z0-9]{3,20}$/', $cleanUsername)){//regular expression
                $this->addError('username', 'Username must be between 3 and 20 characters and alphanumeric.');
        }   else {
            echo "";
            }
        }     
        
    private function validatePassword() {
        $val = ($this->data['password']);
        //hashing with sanitise this
         if(!preg_match('/^[a-zA-Z0-9]{6,12}$/', $val)){//regular expression
                $this->addError('password', 'Password must be between 6 and 12 characters and alphanumeric.');
        }   else {
           echo "";
            }
        }
    
    private function validatePasswordConfirm() {
       $val = ($this->data['password_confirm']);
       $val2 =  ($this->data['password']);
       //hashing with sanitise this
        if ($val ==$val2) {
            echo "";
        }   else {    
            $this->addError('password_confirm', 'Your passwords do not match, please try again.'); 
    }
    }
        
    private function validateLibCode() {
        $val = ($this->data['lib_code']);
        $userType = filter_var($val, FILTER_SANITIZE_STRING);
        if (empty($val)){
            ($userType = "Member");
        } else if 
            ($userType== "Admin"){
            $userType = "Admin";
            echo "";
        } else if 
            ($userType== "Librarian"){ 
            $userType = "Librarian"; 
            echo "";
        } else {
        $this->addError('lib_code', 'That code is incorrect, please try again or contact an administrator');
        }
    }
    
    private function addError($key, $val) { //This is an associative array that stores the errors that are generated by the individual 
        $this->errors[$key] = $val;         //functions for each field as above. $key is data name eg 'password, $val is error message
                                            //to be displayed.
    }
}
